### ISSUE TITLE
Compile the server in windows 

### ISSUE THREAD

**Issue by ThomasStaal** [jean343/RPI-GPU-rdpClient#1]
"Install CMAKE and Boost
In cmake under the Server folder
    Set BOOST_ROOT to the root of the Boost folder
Build, I used Visual Studio"

Can you please specify exactly where to add the Boost folder root?

**Comment by jean343** [comment]
Hello,
Thanks for your interest

I downloaded boost from http://www.boost.org/users/download/
Then, I installed boost in C:\boost_1_51_0 on my machine, feel free to use another PATH.
In Cmake, I added the variable BOOST_ROOT and I set it to "C:\boost_1_51_0"

Hope it helps

**Comment by gpande** [comment]
hello, jean343.

when i compiled server.

there is some error occur like below

Building NVCC (Device) object CMakeFiles/cudalib.dir/Debug/cudalib_generated_color_conversion.cu.obj
1>nvcc : fatal error : nvcc cannot find a supported cl version. Only MSVC 9.0 and MSVC 10.0 are supported

i think this error occurs because of MSVC version. i'm using VS 2012.

which version of visual studio do you use?

and can i get exe file of server?

thank you.

**Comment by jean343** [comment]
Hi,

Thanks for your request.

I did use Visual Studio 2010, but I believe it worked on 2012.
It seems like you don't have the CUDA toolkit installed. Do you have an
nvidia graphic card and do you have the toolkit?

I prefer not sending the exe, but I will if needed

JP
